# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bbs_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.BBS'),
            preserve_default=False,
        ),
    ]
